/-
Copyright 2026 The Beneficial AI Foundation. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Jin Xing Lim
-/
import Mathlib.Algebra.Field.Defs
import Mathlib.Algebra.Module.Defs
import Mathlib.GroupTheory.SpecificGroups.Cyclic
import Mathlib.GroupTheory.Subgroup.Simple
import VCVio.OracleComp.Constructions.SampleableType

/-!
# Prime-order group — the algebraic backbone of the KVAC formalisation

Abstract typeclasses for the algebraic setting of Orrù, *Revisiting
Keyed-Verification Anonymous Credentials*, IACR ePrint 2024/1552 (§3.1).
The paper's prime-order group `G` of order `p` with scalars in `ZMod p` is
modelled abstractly as an abelian group `G` that is cyclic and simple
(equivalently — for a finite abelian group — `G ≃ ZMod p` for prime `p`),
together with a `Module F G` action over a generic field `F`.

Two class abbrevs are exposed:

- `PrimeOrderGroup F G` — the *base* algebraic convention, sufficient for
  abstract syntax / correctness files (`Core/`, `Framework/Syntax`,
  `Framework/Correctness`, `Schemes/*/Construction`, …).
- `SampleableGroup F G` — `PrimeOrderGroup` plus `SampleableType G`, with
  the full set of `Fintype` / `DecidableEq` / `SampleableType` instance
  binders that VCV-io's `$ᵗ` sampling notation needs at the call site.
  Used by security-game files (`Framework/Anonymity`,
  `Framework/Extractability`, scheme `Anonymity` / `Extractability` /
  `OneMoreUnforgeability` files).

## Why a generic field `F`?

Nothing in the framework or in either scheme uses prime-order specificity at
the level of the *algebraic* surface — only at the level of the hardness
assumptions (DL, DDH, q-DL, q-DDHI, gap-DL), which are bound separately via
VCV-io's `CryptoFoundations/HardnessAssumptions/`. Keeping `F` generic makes
the framework directly usable for elliptic curves over arbitrary prime-order
base fields (where `F` is the curve's scalar field) without rewiring the
typeclass stack. Concrete instantiations pick `F := ZMod p` for the
appropriate `p`.

## Notation convention

This formalisation uses **additive notation** throughout, matching O24 §3.1.
The paper's `xG = X` translates directly to Lean's `x • G₀ = X`, where
`G₀ : G` is a generator the scheme picks (typically passed in `Pp`).
See [`docs/STYLE_GUIDE.md`](../../docs/STYLE_GUIDE.md), section *Additive
groups*, for the project-wide rule.

## Out of scope here

- Random-oracle interfaces (`H_p`, `H_G`) — formalised in `KVAC/Core/Hash.lean`.
- Cryptographic hardness assumptions (DL, DDH, q-DL, q-DDHI, gap-DL) —
  bound to VCV-io's `HardnessAssumptions/` in Track Pre (issue #2).
-/

namespace KVAC.Core

/--
A prime-order abelian group `G` with scalars in a generic field `F`.

Bundles the Mathlib typeclass stack used throughout the formalisation:

- `AddCommGroup G` — abelian additive group;
- `Fintype G` — finite, so `Nat.card G` is well-defined;
- `IsAddCyclic G` — generated by a single element. Technically derivable from
  `[AddCommGroup G] [Fintype G] [IsSimpleAddGroup G]` via Mathlib's standard
  "simple abelian finite ⇒ cyclic of prime order" instance; kept explicit for
  self-documentation.
- `IsSimpleAddGroup G` — `G` has no non-trivial normal subgroups (and is
  `Nontrivial`). Combined with abelian + finite, this is equivalent to
  `G ≃ ZMod p` for some prime `p`, i.e. it pins down prime order.
- `Module F G` — `F` acts on `G` via scalar multiplication; unlocks the full
  Mathlib `Module` lemma library (`mul_smul`, `add_smul`, `one_smul`, …) for
  scheme equations.

The class name foregrounds `G`'s identity as a *group* — the `Module F G`
structure is one property among others, not the headline.

`F` is taken as an explicit class parameter (the `[Field F]` binder is
required at the call site); `G` is the carrier of the bundled instances.

Canonical call site:

```lean
variable {F G : Type} [Field F] [PrimeOrderGroup F G]
```

See [`docs/STYLE_GUIDE.md`](../../docs/STYLE_GUIDE.md), section
*Prime-order group convention*, for the project-wide rule.
-/
class abbrev PrimeOrderGroup (F G : Type) [Field F] :=
  AddCommGroup G, Fintype G, IsAddCyclic G, IsSimpleAddGroup G, Module F G

/--
A `PrimeOrderGroup F G` plus the full set of `Fintype` / `DecidableEq` /
`SampleableType` instances needed for game construction via VCV-io's `$ᵗ`
sampling notation. Use this in files that build security games
(`Framework/Anonymity`, `Framework/Extractability`, scheme `Anonymity` /
`Extractability` / `OneMoreUnforgeability` files); abstract-syntax files
that don't sample can use the lighter `PrimeOrderGroup` directly.

The class abbrev bundles what it can as parents (`SampleableType G`,
inherited via `PrimeOrderGroup F G`); the rest are required as explicit
instance binders. `DecidableEq` is not a structure-class and can't appear
as a `class abbrev` parent; the F-side classes can't be bundled because
`class abbrev`'s parents must share a single carrier (and the G-side
parents have carrier `G`). Requiring them as instance binders gives Lean's
elaborator a clear error when one is missing, rather than forcing the
contributor to recall the binder list from documentation.

Canonical call site:

```lean
variable {F : Type} [Field F] [Fintype F] [DecidableEq F] [SampleableType F]
variable {G : Type} [DecidableEq G] [SampleableGroup F G]
```

See [`docs/STYLE_GUIDE.md`](../../docs/STYLE_GUIDE.md), section
*Prime-order group convention*, for the project-wide rule.
-/
class abbrev SampleableGroup (F G : Type)
    [Field F] [Fintype F] [DecidableEq F] [SampleableType F] [DecidableEq G] :=
  PrimeOrderGroup F G, SampleableType G

/--
`SampleableType` instance for a nonempty finite subtype, by transport from
`Fin (Fintype.card _)` via `Fintype.equivFin`. Centralises the
`NeZero (Fintype.card _)` + `SampleableType.ofEquiv (Fintype.equivFin _).symm`
idiom that every uniform-subtype sample needs. The caller supplies the
(site-specific) `Nonempty` witness; the rest is uniform.

Kept as a `def` (not a global `instance`) so a site opts in explicitly — a
global `SampleableType {x // p x}` instance would risk the `SampleableType` /
`Fintype` instance-search derailment the AGM scaffolding carefully avoids
(see `KVAC.Schemes.MicroCMZ.SignMask`). Used by μCMZ's `uniformNonzero` over
`{g : G // g ≠ 0}` and the AGM reduction's non-vanishing signing masks.
-/
noncomputable def SampleableType.ofNonemptySubtype {α : Type} [Fintype α]
    [DecidableEq α] (p : α → Prop) [DecidablePred p]
    (h : Nonempty {x : α // p x}) : SampleableType {x : α // p x} := by
  haveI : Nonempty {x : α // p x} := h
  haveI : NeZero (Fintype.card {x : α // p x}) := ⟨Fintype.card_ne_zero⟩
  exact SampleableType.ofEquiv (Fintype.equivFin {x : α // p x}).symm

end KVAC.Core
