/-
Copyright 2026 The Beneficial AI Foundation. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Semar Augusto
-/
import KVAC.Core.AlgebraicMAC
import KVAC.Core.Group
import VCVio.OracleComp.ProbComp
import VCVio.OracleComp.Constructions.SampleableType

/-!
# μCMZ as an algebraic MAC — construction (O24 §5.1, Figure 9 "Base MAC")

The base MAC underlying the μCMZ keyed-verification credential of Orrù,
*Revisiting Keyed-Verification Anonymous Credentials*, IACR ePrint 2024/1552,
§5.1 (Figure 9). We instantiate the abstract `AlgebraicMACSyntax ProbComp`
(`KVAC.Core.AlgebraicMAC`) with the four algorithms `(S, K, M, V)`, prove the
support-based `Correct` predicate, and bundle them into the paper-level
`AlgebraicMAC` object `μCMZBaseMAC` (the base MAC, not the full
credential).

Everything is stated over the abstract `SampleableGroup F G` from
`KVAC.Core.Group` — no concrete curve. Per the project layering, this file is a
"game-construction" file (it samples), so it uses the `SampleableGroup`
variable block (see `docs/STYLE_GUIDE.md`, *Prime-order group convention*).

## The construction (Figure 9, Base MAC)

- `S(1^λ, n)`: sample `H ←$ G`; `crs := (Γ, H)`. Here `Γ = (G, p, G₀)` is the
  typeclass *except for `G₀`*: `G`/`p` are the `PrimeOrderGroup` typeclass stack,
  while the generator `G₀` is **not** produced by `setup` (which returns only
  `H`). It is supplied by the caller as the parameter `gen : G` — see the
  *Generator as a parameter* section below.
- `K(crs)`: sample `sk = (x₀, xᵣ, x⃗) ←$ Zₚ^{n+2}`;
  `pp = (X₀ = x₀·H, Xᵣ = xᵣ·G₀, Xᵢ = xᵢ·G₀)`, with `G₀` the parameter `gen`.
  Note `X₀` uses the CRS element `H`, while `Xᵣ`/`X⃗` use `gen` — matching
  Figure 9's distinct roles for `H` and `G₀`.
- `M(sk, m⃗)`: sample `U` (see below); `V := (x₀ + xᵣ + Σᵢ xᵢmᵢ)·U`; return
  `σ = (U, V)`.
- `V(sk, m⃗, (U,V))`: return `U ≠ 0 ∧ V = (x₀ + xᵣ + Σᵢ xᵢmᵢ)·U`.

## Nonzero `U` and perfect correctness

The paper's defining MAC equation (Eq. (1) in §5) samples `U ←$ G×` from the
*punctured* group `G× = G ∖ {0}` (in a prime-order group these are exactly the
generators, the standard MAC_GGM reading); only the figures write the looser
`U ←$ G`. We follow Eq. (1). The `verify` algorithm rejects `U = 0` (Figure 9),
so under the figure's `U ←$ G` the honestly produced `(0, 0)` tag would fail
verification — a `1/p` failure mass the figure does not record. Sampling `G×`
per Eq. (1) removes that mass, and the repo's perfect (support-based) `Correct`
predicate (in `KVAC.Core.AlgebraicMAC.Correctness`) is then satisfied as a
direct consequence: every tag in the support of `M` verifies.

The nonzero sampling is realized by `uniformNonzero G : ProbComp G` — it samples
the subtype `{g : G // g ≠ 0}` internally but *projects the `≠ 0` witness away*,
returning a plain `G`. Thus `Tag` stays `G × G` and no downstream
definition/theorem mentions `{g : G // g ≠ 0}`; nonzeroness is recovered on
demand from `mem_support_uniformNonzero` (the `U ≠ 0` check in `verify` is then
just the support hypothesis, not a definitional fact about `U`).

## Generator as a parameter

The generator `G₀` (O24's `G₀ ∈ Γ`, with `Γ = (G, p, G₀)`) is taken as an
explicit scheme parameter `gen : G`, not generated by `setup` and not chosen via
`Classical.choice`. This matches how `KVAC.Preliminaries.Assumptions.lean` and
`KVAC.Schemes.MicroCMZ.Relations.lean` treat the generator (`g`/`gen : G` as a
per-definition parameter), and how O24 carries `G₀` as data inside `Γ`. It feeds
only `keygen` (`Xᵣ = xᵣ·gen`, `Xᵢ = xᵢ·gen`); `verify` never reads `pp`, so the
choice of generator is irrelevant to correctness.

It is *not* a route to a computable scheme: the constructions here remain
`noncomputable` because scalar/group sampling (`$ᵗ F`, `$ᵗ G`, and
`uniformNonzero`) is built on `Fintype.equivFin`, which is itself
`noncomputable`. Removing `Classical.choice` for `G₀` removes *one* source of
noncomputability (and stops using `choice` for data the paper carries
explicitly); obtaining a computable example would additionally require
computable `SampleableType` instances, which is an `Instances/` concern.

## Cross-reference: Signal's `zkgroup` (non-normative)

The deployed Signal analogue is `rust/zkgroup/src/crypto/credentials.rs`
(`KeyPair::generate` / `credential_core`). It is a *different* MAC: a MAC_GGM
variant with group-element attributes `Mᵢ`, a standalone `W = w·G_w` term, a
per-credential system scalar `t`, and the public key packed as `C_W` / `I`, over
Ristretto255 — i.e. `V = W + (x₀ + x₁·t)·U + Σᵢ yᵢ·Mᵢ`. Per the project's
paper-driven layering that deployment is an *instance*, never the framework; this
file follows O24 Figure 9 (`V = (x₀ + xᵣ + Σᵢ xᵢmᵢ)·U`) with scalar attributes
over an abstract group. The pointer is for orientation only.

## Out of scope

- UF-CMVA security (O24 Theorem 5.1, AGM under 3-DL) — needs the AGM model, the
  3-DL assumption, and straight-line extraction, none of which exist yet.
- The full credential protocol (Issue / Present, the predicate `φ`, the ZK
  relations of Eqs. 9–11) — the rest of §5.1. In μCMZ, Issue uses *Pedersen*
  commitments (`C' = Σ mᵢXᵢ + sG`; unblind `V' − sU'`), not the ElGamal
  `D1/D2/E1/E2/S1/S2` path of the libsignal analogue.
-/

namespace KVAC.Schemes.MicroCMZ

open KVAC.Core OracleComp

set_option autoImplicit false

section UniformNonZero
variable {G : Type} [AddCommGroup G] [Fintype G] [DecidableEq G] [Nontrivial G] 

/--
Uniform sampling from the nonzero elements of a nontrivial finite group. The
subtype `{g : G // g ≠ 0}` is a nonempty `Fintype`, so it inherits a
`SampleableType` instance by transport from `Fin (Fintype.card _)`. Noncomputable
via `Fintype.equivFin` (the `(exists_ne …).choose_spec` in the `Nonempty`
witness lives in `Prop` and is erased, so it is not the obstruction).
-/
noncomputable instance instSampleableTypeNeZero : SampleableType {g : G // g ≠ 0} :=
  haveI : Nonempty {g : G // g ≠ 0} := ⟨⟨_, (exists_ne (0 : G)).choose_spec⟩⟩
  haveI : NeZero (Fintype.card {g : G // g ≠ 0}) := ⟨Fintype.card_ne_zero⟩
  SampleableType.ofEquiv (Fintype.equivFin {g : G // g ≠ 0}).symm

/--
Uniform sampling from `G ∖ {0}`, returned as a plain `G`. This is `U ←$ G∖{0}`
with the `≠ 0` witness *projected away*, so the subtype `{g : G // g ≠ 0}` never
leaks into tag types or into downstream definitions/theorems: callers see a
`ProbComp G`, and recover nonzeroness from `mem_support_uniformNonzero` when they
need it (e.g. the correctness proof). Noncomputable via `instSampleableTypeNeZero`.
-/
noncomputable def uniformNonzero (G : Type) [AddCommGroup G] [Fintype G]
  [DecidableEq G] [Nontrivial G] : ProbComp G := do
  let u ← ($ᵗ {g : G // g ≠ 0} : ProbComp {g : G // g ≠ 0})
  pure u.val

/-- The support of `uniformNonzero G` is exactly `G ∖ {0}`: an element is a
possible output iff it is nonzero. Lets downstream proofs reason about the
sampled `U` without ever destructuring the subtype. -/
@[simp] theorem mem_support_uniformNonzero (u : G) :
    u ∈ support (uniformNonzero G) ↔ u ≠ 0 := by
  simp only [uniformNonzero, support_bind, support_uniformSample, support_pure,
    Set.mem_iUnion, Set.mem_singleton_iff, Subtype.exists, Set.mem_univ, exists_prop,
    true_and]
  constructor
  · rintro ⟨a, ha, rfl⟩; exact ha
  · intro h; exact ⟨u, h, rfl⟩

end UniformNonZero
section μCMZBaseMAC

abbrev Key (F : Type) (n : ℕ) : Type := F × F × (Fin n → F)
abbrev Params (G : Type) (n : ℕ) : Type := G × G × (Fin n → G)
abbrev Code (G : Type) : Type := G × G

/- The canonical game-construction variable block (`docs/STYLE_GUIDE.md`,
*Prime-order group convention*). `F` is implicit here: for the helpers below it is
inferred from `sk : Key F n` (or, for `keygen`, from the expected result type), so
threading it explicitly would only add noise at every internal call. It is
reannotated to *explicit* just before the bundle-level defs (`μCMZBaseMACSyntax`,
`μCMZBaseMAC_correct`, `μCMZBaseMAC`), where `F` does *not* appear in the result
type `AlgebraicMACSyntax ProbComp` and so must be supplied at each call site. `G`
is implicit throughout (inferred from the `gen : G` argument). -/
variable {F : Type} [Field F] [Fintype F] [DecidableEq F] [SampleableType F]
variable {G : Type} [DecidableEq G] [SampleableGroup F G]

/-- The MAC scalar `x₀ + xᵣ + Σᵢ xᵢ mᵢ`, shared by `mac` and `verify`. -/
def macScalar {n : ℕ} (sk : Key F n) (m : Fin n → F) : F :=
  let (x₀, xᵣ, x) := sk
  x₀ + xᵣ + ∑ i, x i * m i

/-- `S(1^λ, n)`: sample `H ←$ G`; the CRS is `H`. -/
noncomputable def setup {G : Type} [SampleableType G] (_secParam _n : ℕ) : ProbComp G := $ᵗ G

/-- `K(crs)`: the parameter `H` is the CRS that `setup` produced. -/
noncomputable def keygen {n : ℕ} (H : G) (gen : G) : ProbComp (Key F n × Params G n) := do
  let x₀ ← $ᵗ F
  let xᵣ ← $ᵗ F
  let x  ← $ᵗ (Fin n → F)
  let X₀ := x₀ • H
  let Xᵣ := xᵣ • gen
  let X  := fun i => x i • gen 
  pure ((x₀, xᵣ, x), (X₀, Xᵣ, X))


/-- `M(sk, m⃗)`: sample `U ←$ G×` via `uniformNonzero` (the `≠ 0` witness
projected away, per the module docstring); return `(U, macScalar·U)`. -/
noncomputable def mac {n : ℕ} (sk : Key F n) (m : Fin n → F) : ProbComp (Code G) := do
  let U ← uniformNonzero G
  pure (U, macScalar sk m • U)

/-- `V(sk, m⃗, (U, V))`: `U ≠ 0 ∧ V = macScalar·U`. -/
def verify {n : ℕ} (sk : Key F n) (m : Fin n → F) (t : Code G) : Bool :=
  let (U, V) := t
  decide (U ≠ 0) && decide (V = macScalar sk m • U)

-- Reannotate `F` as explicit for the bundle-level defs below: it does not appear
-- in their result types, so it must be supplied at each call site (see the
-- variable-block comment above). The helpers keep the implicit `{F}` inferred
-- from `sk`.
variable (F)

/-- μCMZ base-MAC as a syntactic algebraic MAC (O24 §5.1, Figure 9 "Base MAC"),
over the abstract `SampleableGroup F G`. The generator `gen : G` (O24's
`G₀ ∈ Γ`) is an explicit parameter — see the module docstring section *Generator
as a parameter* — feeding only `keygen` (`Xᵣ = xᵣ·gen`, `Xᵢ = xᵢ·gen`); `verify`
never reads `pp`, so the choice of generator is irrelevant to correctness.

`F` is explicit because it does not appear in the result type
`AlgebraicMACSyntax ProbComp` (the carrier families `Msg`, `Sk`, … are projected
out of the structure value).

Noncomputable: scalar/group sampling (`$ᵗ F`, `$ᵗ G`, and `uniformNonzero`) is
built on `Fintype.equivFin`, which is `noncomputable`. Taking `gen` as a
parameter removes one source of noncomputability (the old `Classical.choice`
generator) but does not make the scheme computable — a computable example would
additionally require computable `SampleableType` instances (an `Instances/`
concern).

Carrier types:
- `Crs _ _ := G`            — holds `H` (the group description `Γ` is the typeclass);
- `Msg _   := F`            — attributes live in the scalar field;
- `Sk _    := F × F × (Fin n → F)`  — `(x₀, xᵣ, x⃗)`;
- `Pp _    := G × G × (Fin n → G)`  — `(X₀, Xᵣ, X⃗)`;
- `Tag _   := G × G`        — `(U, V)`.
-/
noncomputable def μCMZBaseMACSyntax (gen : G) :
    AlgebraicMACSyntax ProbComp where
  Crs := fun _ _ => G
  Msg := fun _ => F
  Sk := fun {_secParam n} _ => Key F n
  Pp := fun {_secParam n} _ => Params G n
  Tag := fun _ => Code G
  DecidableEqMsg := fun _ => inferInstance
  setup := setup
  keygen := fun {_secParam _} crs => keygen crs gen
  MAC := fun {_secParam _} _ sk m => mac sk m
  verify := fun {_secParam _} _ sk m t => verify sk m t


/--
μCMZ satisfies perfect (support-based) correctness: every honestly produced tag
verifies. The MAC samples a nonzero `U`, so the `U ≠ 0` check passes; the
verification equation `V = (x₀ + xᵣ + Σᵢ xᵢmᵢ)·U` holds by construction (`rfl`),
since `MAC` builds `V` with exactly that scalar.
-/
theorem μCMZBaseMAC_correct (gen : G) : Correct (μCMZBaseMACSyntax F gen) := by
  intro _secParam n crs _hcrs keys _hkeys m sig hsig
  obtain ⟨sk, _pp⟩ := keys
  simp only [μCMZBaseMACSyntax, mac, support_bind, mem_support_uniformNonzero, support_pure,
    Set.mem_iUnion, Set.mem_singleton_iff] at hsig
  obtain ⟨U, hU, rfl⟩ := hsig
  simp only [μCMZBaseMACSyntax, verify, Bool.and_eq_true, decide_eq_true_eq, ne_eq]
  exact ⟨hU, trivial⟩

/--
The paper-level μCMZ base-MAC (O24 Definition 3.1): the syntactic scheme
paired with its correctness proof, over the generator `gen : G` (O24's `G₀ ∈ Γ`).
Noncomputable (via `μCMZBaseMACSyntax`).
-/
noncomputable def μCMZBaseMAC (gen : G) : AlgebraicMAC :=
  ⟨μCMZBaseMACSyntax F gen, μCMZBaseMAC_correct F gen⟩

end μCMZBaseMAC

end KVAC.Schemes.MicroCMZ
